FROM ruby:3.3.4
RUN adduser developer
USER developer
RUN mkdir -p /home/developer /home/developer/app
WORKDIR /home/developer/app
COPY ./Gemfile .
COPY ./Gemfile.lock .
RUN bundle config --global frozen 1 && bundle install
COPY ./ .
USER root
COPY ./entrypoints/docker-entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/docker-entrypoint.sh
ENTRYPOINT ["docker-entrypoint.sh"]
EXPOSE 3000
